import Image from 'next/image';
import { Toaster } from 'sonner';
import '../global.css';

// shadcn/ui sidebar v3.1
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';

// tua sidebar e topbar (client)
import { AppSidebar, RetexTopBar } from '@/components/custom/app-sidebar';

// shadcn/ui breadcrumbs
import { Breadcrumbs } from '@/components/custom/breadcrumbs';
import React from 'react';
import { TooltipProvider } from '@/components/ui/tooltip';
import AuthBootstrapper from './guard/auth-bootstrapper';
import Protected from './guard/guard';

export const metadata = {
  title: 'Welcome to portal',
  description: 'Generated by create-nx-workspace',
};

export default function PortalLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthBootstrapper />
        <Toaster richColors />
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset className="bg-white">
            <RetexTopBar />

            {/* Breadcrumbs */}

            <main className="relative min-h-[calc(100dvh-4rem)] flex flex-col">
              <div className="flex-1 p-4 sm:p-6 lg:p-8">
                <Breadcrumbs />
                <TooltipProvider>
                  <Protected>{children}</Protected>
                </TooltipProvider>
              </div>

              {/* Footer fixed at the bottom */}
              <footer className="w-full flex justify-center items-center py-6 mt-auto">
                <div className="flex flex-col items-center gap-1">
                  <Image
                    src="/assets/logo.png"
                    alt="retex"
                    height={28}
                    width={100}
                    className="h-7 opacity-90"
                    priority
                  />
                  <span className="text-[11px] tracking-wide text-[#0b6b79]">
                    wear. care. share. repeat.
                  </span>
                </div>
              </footer>
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
